# -*- coding: utf-8 -*-
{
    'name': "Timekeeping Module",
    'summary': "OnE-HR's Timekeeping Module",
    'description': "OnE-HR's Timekeeping Module",
    'author': "XWare",
    'website': "https://www.xwareit.net/",
    'category': 'Uncategorized',
    'version': '0.1',
    'depends': ['base', 'hrad'],
    'data': [
        'views/hr_config.xml',
        'views/hr_timekeeping_view.xml',
        # 'wizard/dtr_by_employee_wizard.xml',
        # 'wizard/dtr_by_department_wizard.xml',
        # 'wizard/dtr_by_employment_status_wizard.xml',
        # 'wizard/summary_of_time_wizard.xml',
        'wizard/compute_time_card_wizard.xml',
        'views/hr_time_card_view.xml',
        'views/hr_faceid_logs_view.xml',
        'views/hr_employee_view.xml',
        'views/resource_calendar_view.xml',
        'views/hr_overtime_view.xml',
        'views/hr_batch_ot_requests_view.xml',
        'views/crosschex_faceid_logs_view.xml',
        'views/res_config_settings_view.xml',
        'security/ir.model.access.csv',
    ],
    'license': 'LGPL-3',
}
