# -*- coding: utf-8 -*-
{
    'name': "ONe-HR - Fixed Assets",
    'summary': "ONe-HR's Fixed Assets Module",
    'description': "ONe-HR's Fixed Assets Module",
    'author': "XWare",
    'website': "https://www.xwareit.net/",
    'category': 'Custom',
    'version': '0.1',
    'depends': ['base', 'hrad', 'maintenance', 'hr_maintenance'],
    'data': [
        'wizard/set_custodian_view.xml',
        'wizard/issue_slip_wizard.xml',
        'views/fixed_assets_config.xml',
        'views/fixed_assets_view.xml',
        'views/fa_record_rules.xml',
        'views/fixed_assets_lookup_view.xml',
        'views/hr_employee_view.xml',
        'reports/fa_report_template.xml',
        'reports/fixed_assets_template.xml',
        'wizard/fa_monitoring_by_group_wizard.xml',
        'reports/fa_monitoring_by_group_template.xml',
        'wizard/fa_monitoring_by_dep_wizard.xml',
        'reports/fa_monitoring_by_dep_template.xml',
        'wizard/fa_monitoring_by_custodian_wizard.xml',
        'reports/fa_monitoring_by_custodian_template.xml',
        'wizard/cancelled_fa_wizard.xml',
        'reports/cancelled_fa_template.xml',
        'views/fleet_view.xml',
        'views/maintenance_equipment_view.xml',
        'views/res_company_view.xml',
        'views/maintenance_request_view.xml',
        'views/maintenance_cost_view.xml',
        'security/ir.model.access.csv',
    ],
    'license': 'LGPL-3',
}
